### ISSUE TITLE
models: location.updated timestamp being updated without reason

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-files-rest#116]
During migration we've detected that the Location.updated field is being updated even if no change was made to the model. This could be related to the event listener being too generic:

https://github.com/inveniosoftware/invenio-files-rest/blob/master/invenio_files_rest/models.py#L210-L213

**Comment by Glignos** [comment]
Issue is no longer valid.
We should check on the Zenodo side.

**Comment by Glignos** [comment]
After a conversation with @slint, there might be issues with Locations being updated after modifying Buckets so we should look into this a bit further.

**Comment by Glignos** [comment]
After a closer look there doesn't seem to be any unwanted behavior in the updating of the models.
