### ISSUE TITLE
api: file serving

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-files-rest#15]
- [x] Access control
- [x] Verify performance with many concurrent requests.

**Comment by ddaze** [comment]
For later considerations: [xsendfile](https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/#), [mod_xsendfile](https://tn123.org/mod_xsendfile/)

**Comment by lnielsen** [comment]
Fixed in 023762ea621ae9e3dfe549d3b9fc0823d0e709c2
