### ISSUE TITLE
rest: support download file

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-files-rest#174]
Expose the functionality to suggest to the browser to trigger a file download instead of trying to serve and render it natively even if supported (for example a pdf, a picture, a video).
The proposed idea is to expose a new GET param which replaces the 'filename' param, for example:
GET `/api/files/download=<value>'

The response should set the header `Content-Disposition: attachment` to trigger a download.

See: https://github.com/inveniosoftware/invenio-files-rest/blob/HEAD/invenio_files_rest/helpers.py#L150

**Comment by lnielsen** [comment]
API'wise I would go with:

``/files/<bucket>/<key>?download``

This would also work with getting a specific version:

``/files/<bucket>/<key>?versionId=<uuid>&download``
