### ISSUE TITLE
__repr__ for ObjectVersion doesn't handle unicode

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-files-rest#178]
Probably changing [`ObjectVersion.__repr__`](https://github.com/inveniosoftware/invenio-files-rest/blob/74846ed4468365c72db6e18c34c9818c3ace5c34/invenio_files_rest/models.py#L899-L902) to smoething like:

```python
return u'{}:{}:{}'.format(...)
```

**Comment by jacquerie** [comment]
Heads up that a [similar error](https://github.com/inveniosoftware/invenio-records-files/pull/46) popped up in the past, so I reaffirm [past me's opinion](https://github.com/inveniosoftware/invenio-records-files/pull/46#issuecomment-346648695): there's probably more unicode-related bugs in Invenio's file stack, unicode-focused tests are missing.
