### ISSUE TITLE
migration: CLI tool to run on legacy bibdocfile invenio to dump files metadata

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-files-rest#19]
- [ ] What to do with metadata - files or rest - fire roles/access control
- [ ] Dump JSON file that can be imported on Invenio 3?
- [ ] Support for incremental dumping/loading (to ease downtime on migration).
- [ ] Use Click library.
- [ ] Invenio 1.x vs 2.x? Probably just imports which are different

**Comment by egabancho** [comment]
Closed via https://github.com/inveniosoftware/invenio-migrator/commit/52a4d914c98fb64d112a0acaa35a503ff24cb07a
