### ISSUE TITLE
docs: installation docs missing

### ISSUE THREAD

**Issue by VickySteeves** [inveniosoftware/invenio-files-rest#212]
I went to this URL to get the documentation to install this plugin: https://invenio-files-rest.readthedocs.io/en/latest/installation.html. However, it currently looks like this:

![Screenshot_20190708_131117](https://user-images.githubusercontent.com/10644777/60829039-fed90780-a181-11e9-8681-35e28c69221a.png)

Just wanted to let y'all know! Maybe something is wrong with the build?

**Comment by lnielsen** [comment]
The two weeks we're working on releasing all files related modules, that will include the missing documentation ;-) It will be part of Invenio v3.2 set for release around early Aug, so stay tuned for heavily updated documentation at that point.
