### ISSUE TITLE
Wrong mime type returned for .ttl files

### ISSUE THREAD

**Issue by manonthegithub** [inveniosoftware/invenio-files-rest#263]
Package version (if known): any

## Describe the bug
When using send_stream the wrong mime type `application/octet-stream` is returned for '.ttl' files (`text/turtle` expected)

## Additional context

https://en.wikipedia.org/wiki/Turtle_(syntax)

**Comment by manonthegithub** [comment]
Sorry need more investigation... looks like it works for some versions

**Comment by lnielsen** [comment]
Note also that Files-REST is very restrictive with which MIME types are sent because the user uploaded files are served from the same domain as the app, and thus, we must essentially prevent the browser from rendering most things to avoid XSS attack vectors.
