### ISSUE TITLE
models: ObjectVersion timestamps

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-files-rest#41]
**Problem:**
The only way to order ObjectVersion instances is by using their `created` date. The way we currently set this date is by using `datetime.utcnow`. The problem is that we don't have anything to check that the date is new. If we have any clock drift we might create versions in the past and mess the ordering.

**Solution:**
We just need to check if the created date is after the last ObjectVersion's one. No need to check the clock drift each time as it would not be efficient. Only the version ordering matters.

**Side effect of this solution:**
If there is a time drift in the future, no ObjectVersion can be created once the clock is synchronized again. We also need a big warning for that so that the time can be fixed. As this should happen rarely we don't need to add a mechanism to fix this case right now. It will be the sysadmin's job.

**Comment by jirikuncar** [comment]
Shouldn't `created` date be set by DBMS?

**Comment by nharraud** [comment]
@jirikuncar It would be better yes, but even Postgres can have a time skew.

**Comment by jbenito3** [comment]
@nharraud but normally Postgres would be a different server. So you can always identify such a problem and correct it by comparing dates from DB server and Web worker.
Otherwise, wouldn't we have the same problem for any other kind of object (besides files)?

**Comment by nharraud** [comment]
@jbenito3 Having wrong dates is not an issue most of the time as they are not used for ordering versions. For example, records versioning use incremented numbers. Records also have creation and last update dates but these are just additional information which can be easily fixed.

For Object Version we use the dates for ordering versions. I don't know how we can fix those if they are wrong. It is doable for sure but not easy.

Having big clock skews is normally very rare as tools like NTP prevent it. However if it happens it is better to fail early and just refuse the insert. Of course if it adds a big overhead we can just count on the fact that the clock skew will remain small enough so that no version will be created before the last one.
